kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: gcc
  commands:
  - cat src/main.zig
  - echo
  - echo before program
  - ./bin/zig-return-struct-arm64
  - echo after program $?
